"""
report_exporter.py
-------------------
Build a single, self-contained HTML report with the dataset overview,
AI/rule-based insights, and the auto-generated charts, so the user can
download and share it without needing Streamlit running.
"""

import datetime
import html


def build_html_report(file_name: str, profile: dict, insights_text: str, charts, used_ai: bool) -> str:
    generated_at = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    insight_lines = insights_text.strip().split("\n")
    insight_html = "\n".join(
        f"<li>{html.escape(line.lstrip('- ').strip())}</li>" for line in insight_lines if line.strip()
    )

    charts_html = ""
    plotly_js_included = False
    for title, fig in charts:
        include_js = "cdn" if not plotly_js_included else False
        plotly_js_included = True
        chart_div = fig.to_html(full_html=False, include_plotlyjs=include_js)
        charts_html += f"<div class='chart-block'><h3>{html.escape(title)}</h3>{chart_div}</div>\n"

    missing_html = ""
    if profile.get("missing_pct"):
        rows = "".join(
            f"<tr><td>{html.escape(col)}</td><td>{pct}%</td></tr>"
            for col, pct in profile["missing_pct"].items()
        )
        missing_html = f"""
        <table>
            <thead><tr><th>Column</th><th>Missing %</th></tr></thead>
            <tbody>{rows}</tbody>
        </table>
        """
    else:
        missing_html = "<p>No missing values detected.</p>"

    source_label = "AI-generated" if used_ai else "Rule-based (no AI key configured)"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Data Analysis Report - {html.escape(file_name)}</title>
<style>
    body {{ font-family: -apple-system, Segoe UI, Roboto, Arial, sans-serif; margin: 40px; color: #1a1a1a; background: #fafafa; }}
    h1 {{ margin-bottom: 0; }}
    .subtitle {{ color: #666; margin-top: 4px; }}
    .card {{ background: white; border-radius: 10px; padding: 24px; margin: 20px 0; box-shadow: 0 1px 4px rgba(0,0,0,0.08); }}
    table {{ border-collapse: collapse; width: 100%; }}
    th, td {{ border: 1px solid #e0e0e0; padding: 8px 12px; text-align: left; }}
    th {{ background: #f0f0f0; }}
    .badge {{ display: inline-block; padding: 3px 10px; border-radius: 12px; background: #eef2ff; color: #3730a3; font-size: 12px; }}
    .chart-block {{ margin-bottom: 32px; }}
    ul {{ line-height: 1.8; }}
</style>
</head>
<body>
    <h1>📊 AI Data Analyst Report</h1>
    <p class="subtitle">File: <strong>{html.escape(file_name)}</strong> &middot; Generated {generated_at}</p>

    <div class="card">
        <h2>Overview</h2>
        <p>{profile['n_rows']} rows &middot; {profile['n_cols']} columns &middot; {profile['duplicate_rows']} duplicate rows</p>
        <h3>Missing Data</h3>
        {missing_html}
    </div>

    <div class="card">
        <h2>Business Insights <span class="badge">{source_label}</span></h2>
        <ul>{insight_html}</ul>
    </div>

    <div class="card">
        <h2>Charts</h2>
        {charts_html}
    </div>

    <p style="color:#999;font-size:12px;">Generated by AI Data Analyst.</p>
</body>
</html>
"""
